name: PR Test

on:
  pull_request:
    branches:
      - main
      - development
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:cov

      - name: Publish CTRF Test Summary Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/ctrf-report.json'
          pull-request-report: true
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
